/obj/structure/closet/wardrobe/miner/PopulateContents()
	new /obj/item/storage/backpack/duffelbag/explorer(src)
	new /obj/item/storage/backpack/explorer(src)
	new /obj/item/storage/backpack/satchel/explorer(src)
	new /obj/item/storage/backpack/messenger/explorer(src)
	new /obj/item/clothing/under/rank/cargo/miner/lavaland(src)
	new /obj/item/clothing/under/rank/cargo/miner/lavaland(src)
	new /obj/item/clothing/under/rank/cargo/miner/lavaland(src)
	new /obj/item/clothing/shoes/workboots/mining(src)
	new /obj/item/clothing/shoes/workboots/mining(src)
	new /obj/item/clothing/shoes/workboots/mining(src)
	new /obj/item/clothing/gloves/doppler_mining(src)
	new /obj/item/clothing/gloves/doppler_mining(src)
	new /obj/item/clothing/gloves/doppler_mining(src)
	new /obj/item/clothing/suit/armor/vest/miningjacket(src)
	new /obj/item/clothing/suit/armor/vest/miningjacket(src)
	new /obj/item/clothing/suit/armor/vest/miningjacket(src)
	new /obj/item/clothing/head/mining_cap(src)
	new /obj/item/clothing/head/mining_cap(src)
	new /obj/item/clothing/head/mining_cap(src)

/obj/structure/closet/secure_closet/miner/PopulateContents()
	new /obj/item/stack/sheet/mineral/sandbags(src, 5)
	new /obj/item/storage/box/emptysandbags(src)
	new /obj/item/card/mining_point_card(src)
	new /obj/item/shovel(src)
	new /obj/item/pickaxe/mini(src)
	new /obj/item/radio/headset/headset_cargo/mining(src)
	new /obj/item/flashlight/seclite(src)
	new /obj/item/storage/bag/plants(src)
	new /obj/item/storage/bag/ore(src)
	new /obj/item/mining_scanner(src)
	new /obj/item/clothing/glasses/mining_meson(src)
	new /obj/item/storage/toolbox/guncase/modular/pulse_rifle(src)
	if (HAS_TRAIT(SSstation, STATION_TRAIT_SMALLER_PODS))
		new /obj/item/survivalcapsule/bathroom(src)
	else
		new /obj/item/survivalcapsule(src)
	new /obj/item/assault_pod/mining(src)
